package cmd

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/url"
	"os"
	"strings"
)

func onboardGenerateToken(bytes int) (string, error) {
	b := make([]byte, bytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("crypto/rand failed: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// promptPostgresFields prompts for individual database fields and builds a DSN.
func promptPostgresFields() (string, error) {
	host, err := promptString("Host", "", "localhost")
	if err != nil {
		return "", err
	}
	port, err := promptString("Port", "", "5432")
	if err != nil {
		return "", err
	}
	dbName, err := promptString("Database name", "", "argoclaw")
	if err != nil {
		return "", err
	}
	user, err := promptString("Username", "", "postgres")
	if err != nil {
		return "", err
	}
	password, err := promptPassword("Password", "Leave empty if no password")
	if err != nil {
		return "", err
	}
	sslMode, err := promptString("SSL mode", "", "disable")
	if err != nil {
		return "", err
	}

	// Build DSN with proper escaping
	var userInfo *url.Userinfo
	if password != "" {
		userInfo = url.UserPassword(user, password)
	} else {
		userInfo = url.User(user)
	}
	dsn := fmt.Sprintf("postgres://%s@%s:%s/%s?sslmode=%s", userInfo.String(), host, port, dbName, sslMode)
	return dsn, nil
}

// onboardWriteEnvFile writes the minimal .env.local with only the 3 required secrets.
// Values are single-quoted to prevent bash from interpreting special characters
// (e.g. $, !, spaces) in passwords or keys.
func onboardWriteEnvFile(path, postgresDSN, gatewayToken, encryptionKey string) error {
	var lines []string
	lines = append(lines, "# ArgoClaw — auto-generated by onboard")
	lines = append(lines, "# Keep this file secret! Add to .gitignore.")
	lines = append(lines, "")
	lines = append(lines, fmt.Sprintf("export ARGOCLAW_POSTGRES_DSN='%s'", postgresDSN))
	lines = append(lines, fmt.Sprintf("export ARGOCLAW_GATEWAY_TOKEN='%s'", gatewayToken))
	lines = append(lines, fmt.Sprintf("export ARGOCLAW_ENCRYPTION_KEY='%s'", encryptionKey))
	lines = append(lines, "")

	content := strings.Join(lines, "\n")
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write env file: %w", err)
	}
	return nil
}
